[package]
name = "parser_driver"
version = "0.1.0"
edition = "2024"

[dependencies]
shared = { path = "../../shared"}
ast = { path = "../../ast"}
source = { path = "../../source"}
parser = { path = "../parser"}
io = { path = "../../io"}
